length = float(input("What's the length?:"))
width = float(input("What's the width?:"))
area = float(length * width)
print(f"Here is the area:", area)
perimeter = float(2 * (length + width))
print(f"Here is the perimeter:", perimeter)
